Repository Teamie-UMC-8th/Teamie-front, pull requests merged in 2025-07, with the labels that each got.

#4 [Feat/1] Navbar 컴포넌트 기능 구현 및 메뉴 세팅
  public/icons/arrow-down.svg
  public/icons/calendar.svg
  public/icons/create-project.svg
  public/icons/dashboard.svg
  public/icons/files.svg
  public/icons/home.svg
  public/icons/join-project.svg
  public/icons/profile.svg
  public/icons/retrospect.svg
  public/icons/task.svg
  public/icons/team-calendar.svg
  src/app/home/calendar/page.tsx
  src/app/home/page.tsx
  src/app/home/tasks/page.tsx
  src/app/layout.tsx
  src/app/new/create/page.tsx
  src/app/new/join/page.tsx
  src/app/new/page.tsx
  src/app/page.tsx
  src/app/projects/calendar/page.tsx
  src/app/projects/dashboard/page.tsx
  src/app/projects/files/page.tsx
  src/app/projects/home/page.tsx
  src/app/projects/page.tsx
  src/app/projects/retrospect/page.tsx
  src/components/Navbar.tsx
  src/components/Sidebar.tsx
  src/types/.gitkeep
  src/types/sidebar.ts
Labels: ✨ Feature

#6 [Feat/5] 팀 일정 상세페이지 UI 구현
  pnpm-lock.yaml
  public/icons/addPerson.svg
  public/icons/dayPicker.svg
  public/icons/timePicker.svg
  src/app/projects/calendar/page.tsx
Labels: ✨ Feature

#7 [Feat/2] 업무 대시보드 페이지 UI 구현
  .gitignore
  package-lock.json
  package.json
  pnpm-lock.yaml
  public/icons/assignee.svg
  public/icons/filter.svg
  public/icons/search.svg
  src/app/layout.tsx
  src/app/projects/dashboard/page.tsx
  src/components/Searchbar.tsx
  src/components/Sidebar.tsx
  src/components/TaskItem.tsx
  src/components/ToggleButton.tsx
  src/constants/constants.ts
  src/constants/mockData.ts
  src/features/.gitkeep
  src/features/boards/StatusBoard.tsx
  src/features/boards/StepsBoard.tsx
  src/features/boards/components/AddTaskButton.tsx
  src/features/boards/components/StepHeader.tsx
  src/features/boards/hooks/useSteps.ts
  src/utils/formatDate.ts
Labels: ✨ Feature

#10 [Feat/3] 업무 상세 페이지 + AI포트폴리오 페이지 UI 구현
  pnpm-workspace.yaml
  public/icons/AiPortfolioCreate.svg
  public/icons/AiPortfolioCreateinactive.svg
  public/icons/arrow-left.svg
  public/icons/comment-enter.svg
  public/icons/comment-profile.svg
  public/icons/deadline-calendar.svg
  public/icons/delete.svg
  public/icons/drop-down.svg
  public/icons/file-upload.svg
  public/icons/mi_circle-information.svg
  public/icons/plus-circle.svg
  public/icons/toggledesign.svg
  src/app/mypage/aiportfolio/page.tsx
  src/app/mypage/page.tsx
  src/app/projects/[projectId]/tasks/[taskId]/page.tsx
  src/components/Navbar.tsx
Labels: ✨ Feature

#22 [Feat/11] 개인 회고 페이지 함수 분리/디자인 수정
  src/app/(main)/mypage/aimasterportfolio/page.tsx
  src/app/(main)/mypage/page.tsx
  src/app/(main)/projects/[projectId]/retrospect/page.tsx
  src/components/DeleteButton.tsx
  src/features/retrospects/components/PersonalSection.tsx
Labels: ✨ Feature

#29 [Feat/13]AI 마스터 포트폴리오 UI 구현
  src/app/(main)/mypage/aimasterportfolio/page.tsx
  src/components/DeleteButtonModal.tsx
  src/features/aimasterportfolio/components/ManualWriteSection.tsx
Labels: ✨ Feature

#30 [Feat/20] 삭제 버튼 컴포넌트 구현
  src/app/(main)/mypage/aimasterportfolio/page.tsx
  src/components/DeleteButton.tsx
  src/components/DeleteButtonModal.tsx
Labels: ✨ Feature

#36 [Feat/13] AI 마스터 포트폴리오 UI 구현
  public/icons/spike-left.svg
  public/icons/spike-right.svg
  src/app/(main)/mypage/aimasterportfolio/create/page.tsx
  src/app/(main)/mypage/aimasterportfolio/final/page.tsx
  src/app/(main)/mypage/aimasterportfolio/page.tsx
  src/app/(main)/projects/[projectId]/retrospect/create/page.tsx
  src/app/(main)/projects/[projectId]/retrospect/page.tsx
  src/components/Portal.tsx
  src/features/aimasterportfolio/components/AIGenerationSection.tsx
  src/features/aimasterportfolio/components/ManualWriteSection.tsx
  src/features/aimasterportfolio/components/StepSidebar.tsx
  src/features/aimasterportfolio/components/steps/Step1.tsx
  src/features/aimasterportfolio/components/steps/Step2.tsx
  src/features/aimasterportfolio/components/steps/Step3.tsx
  src/features/aimasterportfolio/hooks/useFunnel.tsx
  src/features/retrospects/components/LeaderView.tsx
  src/features/retrospects/components/MemberView.tsx
Labels: ✨ Feature

#39 [Feat/20] 삭제 버튼 컴포넌트 구현
  src/components/DeleteButton.tsx
  src/components/DeleteButtonModal.tsx
Labels: ✨ Feature

#40 [Feat/33] 업무 대시보드 UI/UX 개선
  package.json
  pnpm-lock.yaml
  public/icons/delete_steps.svg
  src/components/TaskItem.tsx
  src/features/boards/StepsBoard.tsx
  src/features/boards/components/StepHeader.tsx
  src/features/boards/hooks/useSteps.ts
Labels: ✨ Feature

#45 [Feat/13] AI 마스터 포트폴리오 UI 구현
  src/app/(main)/mypage/aimasterportfolio/create/ai/page.tsx
  src/app/(main)/mypage/aimasterportfolio/create/manual/page.tsx
  src/app/(main)/mypage/aimasterportfolio/final/page.tsx
  src/app/(main)/mypage/aimasterportfolio/page.tsx
  src/features/aimasterportfolio/components/AIGenerationSection.tsx
Labels: ✨ Feature

#51 [Feat/50] 뒤로가기 버튼 공용 컴포넌트 구현
  src/app/(main)/projects/[projectId]/tasks/[taskId]/page.tsx
  src/components/BackButton.tsx
Labels: ✨ Feature

#52 [Feat/44] 나의 업무 페이지 반응형 UI 구현
  src/app/(main)/home/tasks/page.tsx
  src/app/(main)/layout.tsx
  src/app/(main)/new/create/page.tsx
  src/app/(main)/new/join/page.tsx
  src/app/(main)/new/page.tsx
  src/components/Navbar.tsx
  src/components/ProfileDropdown.tsx
  src/components/Sidebar.tsx
  src/features/boards/MyTaskBoard.tsx
  src/features/boards/components/ProjectHeader.tsx
  src/utils/url.ts
Labels: ✨ Feature

#56 [Style/55] 업무 상세페이지 UI 요소 수정
  public/icons/jpg-file.svg
  public/icons/jpg-icon.svg
  public/icons/pdf-file.svg
  public/icons/pdf-icon.svg
  public/icons/png-file.svg
  public/icons/png-icon.svg
  public/icons/txt-file.svg
  public/icons/txt-icon.svg
  src/app/(main)/projects/[projectId]/tasks/[taskId]/page.tsx
  src/features/tasks/components/AddComment.tsx
  src/features/tasks/components/CommentDropdown.tsx
  src/features/tasks/components/FileUploader.tsx
  src/features/tasks/components/ReplyComment.tsx
Labels: 🎨 Style

#60 [Feat/53] 업무 대시보드 페이지 반응형 UI 구현
  src/app/(main)/projects/[projectId]/dashboard/page.tsx
  src/components/Searchbar.tsx
  src/components/ToggleButton.tsx
  src/features/boards/StatusBoard.tsx
  src/features/boards/StepsBoard.tsx
  src/features/boards/components/AddTaskButton.tsx
  src/features/boards/components/StepHeader.tsx
Labels: ✨ Feature

#66 [Feat/63] 프로젝트 생성 페이지 UI 구현
  public/icons/copy_url.svg
  src/app/(main)/new/page.tsx
Labels: ✨ Feature

#68 [Feat/67] API 연동 전 공용 axiosInstance.ts 구현
  src/lib/axiosInstance.ts
  src/services/user/useUser.ts
Labels: ✨ Feature

#78 [Feat/70] 프로젝트 생성 페이지 API 연동
  src/app/(main)/layout.tsx
  src/app/(main)/new/page.tsx
  src/app/layout.tsx
  src/hooks/mutations/useCreateProject.ts
  src/lib/.gitkeep
  src/services/.gitkeep
  src/services/projects/createProject.ts
  src/types/api/project.ts
Labels: ✨ Feature

#90 [Feat/80] 로그인 페이지 API 연동
  src/app/(auth)/layout.tsx
  src/app/(auth)/login/layout.tsx
  src/app/(auth)/login/page.tsx
  src/app/layout.tsx
  src/contexts/AuthContext.tsx
  src/types/api/user.ts
Labels: ✨ Feature

#89 [Feat/85] 프로젝트 홈 UI 구현
  public/icons/Duties.svg
  public/icons/Leader-Icon.svg
  public/icons/PlanIcon.svg
  public/icons/Post-it.svg
  src/app/(main)/projects/[projectId]/page.tsx
  src/features/projectHome/components/PostIt.tsx
Labels: ✨ Feature

#94 [Feat/77] 마이페이지 API 연동
  public/icons/CreditIcon.svg
  src/app/(main)/mypage/aimasterportfolio/[portfolioId]/page.tsx
  src/app/(main)/mypage/page.tsx
  src/features/mypage/components/AddCorrectionButton.tsx
  src/features/mypage/components/Projects.tsx
  src/hooks/mutations/useMasterPortfolio.ts
  src/hooks/mutations/useUser.ts
  src/services/masterportfolio/masterportfolio.ts
  src/services/user/useUser.ts
  src/services/user/user.ts
  src/types/api/masterportfolio.ts
  src/types/api/user.ts
  src/utils/formatDate.ts
Labels: ✨ Feature

#97 [Feat/76] 개인 회고 페이지 api 연동
  src/hooks/Queries/useGetPersonalRetro.ts
Labels: ✨ Feature

#99 [Feat/79] 프로젝트 참여 페이지 UI 구현 및 API 연동
  src/app/(main)/new/page.tsx
  src/app/(main)/projects/join/[inviteCode]/page.tsx
  src/hooks/mutations/useJoinProject.ts
  src/hooks/queries/useGetProject.ts
  src/lib/axiosInstance.ts
  src/services/projects/createProject.ts
  src/services/projects/useProject.ts
  src/types/api/project.ts
  src/utils/formatDate.ts
Labels: ✨ Feature

#100 [Refactor/96] 프로젝트 생성 페이지 리팩토링
  src/app/(auth)/callback/page.tsx
  src/app/(main)/new/page.tsx
  src/app/(main)/projects/join/[inviteCode]/page.tsx
  src/contexts/AuthContext.tsx
  src/hooks/mutations/useCreateProject.ts
  src/services/projects/useProject.ts
  src/types/api/project.ts
Labels: ♻️ Refactor
