Repository Teamie-UMC-8th/Teamie-front, pull requests merged in 2025-08, with the labels that each got.

#116 [Design/115] 로그인 페이지 그라데이션 색상 수정
  src/app/(auth)/login/page.tsx
Labels: 🎨 Style

#118 [Refactor/117] 프로젝트 생성/참여 수정사항 반영
  src/app/(main)/new/page.tsx
  src/app/(main)/projects/join/[inviteCode]/page.tsx
  src/hooks/queries/useGetProject.ts
  src/services/user/user.ts
Labels: ♻️ Refactor

#126 [Feat/108] 업무 대시보드 페이지 API 연결
  src/app/(main)/projects/[projectId]/dashboard/page.tsx
  src/components/TaskItem.tsx
  src/components/ToggleButton.tsx
  src/constants/mockData.ts
  src/features/boards/MyTaskBoard.tsx
  src/features/boards/StatusBoard.tsx
  src/features/boards/StepsBoard.tsx
  src/features/boards/components/AddTaskButton.tsx
  src/features/boards/components/StepHeader.tsx
  src/features/boards/hooks/useSteps.ts
  src/features/boards/hooks/useTaskItems.ts
  src/hooks/mutations/useCreateStep.ts
  src/hooks/mutations/useCreateTask.ts
  src/hooks/mutations/useDeleteStep.ts
  src/hooks/mutations/useUpdateStep.ts
  src/hooks/queries/useGetDashboard.ts
  src/services/dashboard/dashboard.ts
  src/types/api/dashboard.ts
  src/types/api/error.ts
  src/types/api/project.ts
  src/types/api/steps.ts
  src/types/api/taskDetail.ts
  src/types/api/tasks.ts
  src/types/api/user.ts
  src/types/board.ts
Labels: ✨ Feature

#129 [Feat/128] 프로젝트 홈 페이지 API 오류 해결
  src/app/(main)/projects/[projectId]/page.tsx
  src/components/TeamMemberCard.tsx
  src/features/projectHome/components/AddTeamProfileModal.tsx
  src/features/projectHome/components/PostItModal.tsx
  src/features/projectHome/components/TeamMemberCard.tsx
  src/hooks/mutations/useProjectHome.ts
  src/services/ProjectHome/projectHome.ts
Labels: ✨ Feature

#130 [Feat/110] 팀 일정 상세페이지 컴포넌트, API 연동
  src/app/(main)/projects/[projectId]/tasks/[taskId]/page.tsx
  src/app/(main)/projects/[projectId]/teamcalendar/[planId]/teamtask/page.tsx
  src/components/AddProfileButton.tsx
  src/components/DatePicker.tsx
  src/components/DayPicker.tsx
  src/components/TimePicker.tsx
  src/features/teamTask/components/MeetingRecordsField.tsx
  src/features/teamTask/components/MemoField.tsx
  src/features/teamTask/components/RemindMessageButton.tsx
  src/features/teamTask/components/RemindMessageModal.tsx
  src/hooks/mutations/usePlan.ts
  src/hooks/mutations/usePlans.ts
  src/hooks/queries/useGetPlanDetail.ts
  src/services/plans/plan.ts
  src/services/plans/plans.ts
  src/types/api/plans.ts
Labels: ✨ Feature

#132 [Feat/111] 업무 상세페이지 DatePicker 컴포넌트 반영, API 테스트
  public/icons/file-icon.svg
  public/icons/file-preview.svg
  src/app/(main)/home/calendar/page.tsx
  src/app/(main)/projects/[projectId]/files/page.tsx
  src/app/(main)/projects/[projectId]/tasks/[taskId]/page.tsx
  src/components/AddProfileButton.tsx
  src/constants/commentMockData.ts
  src/constants/fileUploadMockData.ts
  src/constants/projectHomeMockData.ts
  src/constants/taskDetailMockData.ts
  src/features/correction/components/TailoredDropdown.tsx
  src/features/tasks/components/AddComment.tsx
  src/features/tasks/components/CommentDropdown.tsx
  src/features/tasks/components/EditComment.tsx
  src/features/tasks/components/FileUploader.tsx
  src/features/tasks/components/ReplyComment.tsx
  src/features/tasks/components/TaskDropdown.tsx
  src/hooks/mutations/useCommentMutations.ts
  src/hooks/mutations/useFileUploadMutations.ts
  src/hooks/mutations/useTaskDetail.ts
  src/services/ProjectHome/projectHome.ts
  src/services/taskDetail/addComment.ts
  src/services/taskDetail/checkTaskDetail.ts
  src/services/taskDetail/uploadFile.ts
  src/types/api/comment.ts
  src/types/api/fileUpload.ts
  src/types/api/taskDetail.ts
  src/types/api/tasks.ts
Labels: ✨ Feature

#142 [Feat/140] 나의 업무 페이지 API 연결
  src/app/(auth)/login/page.tsx
  src/components/TaskItem.tsx
  src/features/boards/MyTaskBoard.tsx
  src/features/boards/StepsBoard.tsx
  src/hooks/queries/useGetMyTasks.ts
  src/services/tasks/myTask.ts
  src/types/api/tasks.ts
Labels: ✨ Feature

#146 [Feat/134] 프로젝트홈 수정사항 반영
  src/app/(main)/projects/[projectId]/page.tsx
  src/components/TeamMemberCard.tsx
  src/features/boards/components/AddTaskButton.tsx
Labels: ✨ Feature

#152 [Fix/137] 프로젝트 참여 실패 시 에러 메세지 렌더링 없이 홈으로 쫓겨나는 현상 수정
  public/icons/welcomeTeamie.svg
  src/app/(main)/projects/join/[inviteCode]/page.tsx
  src/components/TaskItem.tsx
  src/features/boards/MyTaskBoard.tsx
  src/features/boards/StatusBoard.tsx
  src/features/boards/StepsBoard.tsx
  src/types/api/error.ts
  src/types/api/project.ts
  src/types/api/tasks.ts
Labels: 🐛 Bug

#154 [Feat /151] 팀 캘린더 일정 반영 추가
  src/app/(main)/projects/[projectId]/teamcalendar/page.tsx
  src/features/teamclendar/CustomDateCellWrapper.tsx
  src/features/teamclendar/components/CalendarEventBox.tsx
Labels: ✨ Feature

#170 [Feat/131] 업무 대시보드 페이지 DnD로 STEP 이동 기능 추가
  src/app/(main)/projects/[projectId]/dashboard/page.tsx
  src/components/TaskItem.tsx
  src/features/boards/StatusBoard.tsx
  src/features/boards/StepsBoard.tsx
  src/hooks/mutations/useUpdateTaskStep.ts
  src/services/steps/updateTaskStep.ts
  src/types/api/steps.ts
Labels: ✨ Feature

#167 [Feat/151] 팀캘린더 웹소켓 연결
  src/app/(main)/projects/[projectId]/teamcalendar/page.tsx
  src/features/teamclendar/CustomDateCellWrapper.tsx
  src/features/teamclendar/components/CalendarEventBox.tsx
Labels: ✨ Feature

#175 [Feat/174] 구현 안 된 페이지 AI 캐릭터 교체
  public/icons/constructionTeamie.svg
  src/app/(main)/home/calendar/page.tsx
  src/app/(main)/projects/[projectId]/files/page.tsx
Labels: ✨ Feature

#186 [Feat/185] Navbar 수정사항 반영
  next.config.ts
  src/components/Dropdown.tsx
  src/components/Navbar.tsx
Labels: ✨ Feature

#188 [Feat/187] 프로젝트 참여 페이지 리다이렉트
  src/app/(main)/projects/join/[inviteCode]/page.tsx
Labels: ✨ Feature

#192 [Feat/191] 프로젝트 홈 즉시 리다이렉트
  src/app/(main)/projects/join/[inviteCode]/page.tsx
  src/components/Navbar.tsx
Labels: ✨ Feature

#194 [Feat/193] 업무 카드 리다이렉트
  src/features/boards/MyTaskBoard.tsx
  src/features/boards/components/AddTaskButton.tsx
Labels: ✨ Feature

#204 [Fix/199] 팀 캘린더 UI 표시 에러
  src/app/(main)/projects/[projectId]/teamcalendar/page.tsx
  src/features/teamclendar/components/CalendarEventBox.tsx
Labels: 🐛 Bug

#207 [Feat/196] 로그아웃 기능 구현
  src/components/Dropdown.tsx
  src/components/Navbar.tsx
  src/contexts/AuthContext.tsx
  src/hooks/mutations/useLogout.ts
  src/types/api/logout.ts
Labels: ✨ Feature

#212 [Bug/202] 폴더명 import 오류, 오타 수정
  src/app/(main)/mypage/addcorrection/analyzefin/page.tsx
  src/app/(main)/mypage/addcorrection/analyzing/page.tsx
  src/app/(main)/mypage/addcorrection/page.tsx
  src/app/(main)/mypage/addcorrection/projectSelect/page.tsx
  src/app/(main)/mypage/aimasterportfolio/[portfolioId]/create/ai/page.tsx
  src/app/(main)/mypage/aimasterportfolio/[portfolioId]/page.tsx
  src/app/(main)/mypage/page.tsx
  src/app/(main)/mypage/tailoredportfolio/[correctionId]/page.tsx
  src/app/(main)/projects/[projectId]/teamcalendar/page.tsx
  src/app/layout.tsx
  src/components/Navbar.tsx
  src/components/Sidebar.tsx
  src/features/aimasterportfolio/components/AIGenerationSection.tsx
  src/features/aimasterportfolio/components/StepSidebar.tsx
  src/features/correction/components/AddLoadingModal.tsx
  src/features/correction/components/CorrectionResponsiveHeader.tsx
  src/features/correction/components/CorrectionSidebar.tsx
  src/features/mypage/components/AddCorrectionButton.tsx
  src/features/mypage/components/Projects.tsx
  src/features/mypage/components/Tailored.tsx
  src/features/teamCalendar/CalendarButton.tsx
  src/features/teamCalendar/CustomDateCellWrapper.tsx
  src/features/teamCalendar/components/CalendarEventBox.tsx
  src/hooks/mutations/usePatchMasterPortfolio.ts
  src/hooks/mutations/usePatchMasterPortfolioQuestions.ts
  src/hooks/mutations/usePostMasterPortfolioGenerate.ts
  src/hooks/mutations/usePostMasterPortfolioQuestions.ts
  src/hooks/mutations/usePostTeamCalendar.ts
  src/hooks/queries/useGetMasterPortfolio.ts
  src/hooks/queries/useGetTeamCalendar.ts
Labels: 🐛 Bug

#220 [Fix/219] 팀캘린더 페이지 라우팅 경로 오류
  src/constants/menus.ts
Labels: 🐛 Bug

#257 [Feat/251] 개인회고/마스터 포트폴리오 모달 공통 인터랙션 반영
  src/features/aimasterportfolio/components/AIConfirmModal.tsx
  src/features/retrospects/components/ConfirmLeaveModal.tsx
  src/features/retrospects/components/FinalLeaveModal.tsx
  src/features/retrospects/components/ProjectEndModal.tsx
Labels: ✨ Feature

#259 [Fix/256] 프로젝트 참여 페이지 레이아웃 수정
  src/app/(main)/projects/join/[inviteCode]/page.tsx
Labels: 🐛 Bug

#262 [Fix/261] 로그인 유효성 중복 체크 로직 수정
  src/app/layout.tsx
  src/contexts/AuthContext.tsx
  src/hooks/mutations/useUser.ts
  src/lib/axiosInstance.ts
Labels: 🐛 Bug

#268 [Design/267] CopyModal bg 추가
  src/components/CopyModal.tsx
Labels: 🎨 Style

#273 [Feat/217] 업무 상세페이지 수정사항 반영
  src/app/(main)/projects/[projectId]/tasks/[taskId]/page.tsx
  src/components/DeleteButtonModal.tsx
  src/features/tasks/components/AddComment.tsx
  src/features/tasks/components/EditComment.tsx
  src/features/tasks/components/FileUploader.tsx
  src/features/tasks/components/MemoField.tsx
  src/features/tasks/components/ReplyComment.tsx
  src/features/tasks/components/TaskDropdown.tsx
Labels: ✨ Feature

#280 [Fix/264]QA 1차 수정
  src/app/(main)/mypage/aimasterportfolio/[portfolioId]/create/ai/page.tsx
  src/app/(main)/mypage/aimasterportfolio/[portfolioId]/page.tsx
  src/app/(main)/projects/[projectId]/retrospect/create/page.tsx
  src/app/(main)/projects/[projectId]/retrospect/page.tsx
  src/components/ContributionSlider.tsx
  src/features/aimasterportfolio/components/MenuButton.tsx
  src/features/aimasterportfolio/components/StepSidebar.tsx
  src/features/retrospects/components/LeaderView.tsx
  src/features/retrospects/components/MemberView.tsx
  src/features/retrospects/components/PersonalSection.tsx
Labels: 🐛 Bug

#282 [Feat/215] 프로젝트 홈 관련 수정사항 반영
  src/app/(main)/projects/[projectId]/page.tsx
  src/components/TeamMemberCard.tsx
  src/features/projectHome/components/PostIt.tsx
  src/features/projectHome/components/TextFieldModal.tsx
  src/hooks/mutations/useProjectHome.ts
  src/services/ProjectHome/projectHome.ts
Labels: ✨ Feature

#285 [Fix/281] 남의 프로젝트 진입 시에 안 튕기고 에러 메세지만 출력되는 현상 해결
  src/lib/axiosInstance.ts
Labels: 🐛 Bug

#287 [Feat/255] 팀캘린더 디자인,일자 크기, 간격 수정
  src/app/(main)/projects/[projectId]/teamcalendar/page.tsx
  src/features/teamCalendar/components/CalendarEventBox.tsx
  src/hooks/mutations/usePlan.ts
  src/styles/globals.css
Labels: ✨ Feature

#290 [Fix/289] 오늘 날짜에 일정 추가 안되는 문제
  src/features/teamCalendar/CustomDateCellWrapper.tsx
  src/hooks/mutations/usePlan.ts
Labels: 🐛 Bug

#294 [Feat/293] 개인 회고 패딩 조절
  src/app/(main)/mypage/aimasterportfolio/[portfolioId]/create/ai/page.tsx
  src/app/(main)/projects/[projectId]/retrospect/page.tsx
Labels: ✨ Feature

#296 [Feat/286] 드롭다운 외부 클릭 시 닫힘
  src/components/Dropdown.tsx
  src/components/Navbar.tsx
  src/features/aimasterportfolio/components/MenuButton.tsx
Labels: ✨ Feature

#297 [Fix/244] 업무 대시보드 페이지 필터 패널 안 닫히던 오류 수정
  src/app/(main)/projects/[projectId]/dashboard/page.tsx
  src/components/FilterPanel.tsx
  src/components/MiniDatePicker.tsx
  src/components/Searchbar.tsx
Labels: 🐛 Bug

#299 [Fix/291] 호버랑 플러스 버튼 뜨는 날짜 조정하기/프로젝트 생성일에 일정 추가 안되는 문제
  src/app/(main)/projects/[projectId]/teamcalendar/page.tsx
  src/features/teamCalendar/CustomDateCellWrapper.tsx
Labels: 🐛 Bug

#305 [Feat/295] AI 첨삭 페이지 3차 수정사항 반영
  src/app/(main)/mypage/addcorrection/analyzing/page.tsx
  src/app/(main)/mypage/addcorrection/correctionIntro/page.tsx
  src/app/(main)/mypage/addcorrection/layout.tsx
  src/app/(main)/mypage/addcorrection/projectSelect/page.tsx
  src/app/(main)/mypage/tailoredportfolio/[correctionId]/page.tsx
  src/utils/formatDate.ts
Labels: ✨ Feature

#308 [BUG/303] 참석자 선택 컴포넌트 프로필 정렬 순서, 깜빡이는 오류
  src/app/(main)/projects/[projectId]/tasks/[taskId]/page.tsx
  src/components/AddProfileButton.tsx
Labels: 🐛 Bug

#309 [Feat/304] 일반 유저일 때 AI 첨삭 카드가 나오지 않도록 수정
  src/app/(main)/mypage/page.tsx
Labels: ✨ Feature

#310 [Feat/307] 팀 일정 상세페이지 리마인드 메시지 링크 구현
  src/app/(main)/projects/[projectId]/teamcalendar/[planId]/teamtask/page.tsx
  src/features/teamTask/components/RemindMessageModal.tsx
  src/utils/url.ts
Labels: ✨ Feature

#316 [Feat/315] 마스터 포트폴로오 질문 페이지 예/아니오 글씨 수정, 뒤로가기 버튼 영역 수정
  src/app/(main)/mypage/aimasterportfolio/[portfolioId]/page.tsx
  src/features/aimasterportfolio/components/steps/Step3.tsx
Labels: ✨ Feature

#318 [Fix/317] 개인 회고 반응형 수정
  src/features/retrospects/components/EditableMarkdown.tsx
  src/features/retrospects/components/PersonalSection.tsx
Labels: 🐛 Bug

#322 [Fix/321] 생성중일 때 모달 디자인 수정
  src/app/(main)/mypage/aimasterportfolio/[portfolioId]/create/ai/page.tsx
  src/app/(main)/mypage/aimasterportfolio/[portfolioId]/page.tsx
Labels: 🐛 Bug

#323 [Feat/263] 리프레시 토큰 추가
  src/app/(main)/new/page.tsx
  src/app/layout.tsx
  src/contexts/AuthContext.tsx
  src/hooks/mutations/useUser.ts
  src/hooks/useThrottle.ts
  src/lib/axiosInstance.ts
  src/lib/queryClient.ts
  src/services/auth/refreshToken.ts
  src/services/user/user.ts
  src/utils/authRoute.ts
Labels: ✨ Feature
